services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
  api:
    build: ./api
    container_name: video_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - STORAGE_PATH=/data
    volumes:
      - ./data:/data
    depends_on:
      - redis
  worker:
    build: ./worker
    container_name: video_worker
    restart: unless-stopped
    environment:
      - STORAGE_PATH=/data
    volumes:
      - ./data:/data
    depends_on:
      - redis

volumes:
  redisdata: