services:

  api:
    build: ./api
    container_name: video_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - STORAGE_PATH=/data
    volumes:
      - ./data:/data